### ISSUE TITLE
Divisione lavori

### ISSUE THREAD

**Issue by Radish0** [lorenzobotti/esercizio_github#1]
Io farei volentieri il primo punto, creo una nuova pagina?

**Comment by lorenzobotti** [comment]
Ci sta, io pensavo di scrivere la guida in [markdown](https://www.markdownguide.org/basic-syntax) perchè quando hai codice e testo insieme in html è difficile lavorarci

**Comment by Radish0** [comment]
Quindi non vuoi più fare una cosa in html? O l'html e il markdown assieme?

**Comment by giomape** [comment]
Io posso fare qualunque cosa

**Comment by Radish0** [comment]
Guarda i punti in todos.md e scegli un punto che vuoi fare, almeno ci dividiamo per bene

**Comment by lorenzobotti** [comment]
No, il markdown [viene compilato in html](https://dillinger.io/), ma è più veloce da leggere e scrivere e visto che tanti lavoriamo sulla stessa cosa credo sia una scelta migliore

**Comment by lorenzobotti** [comment]
Nel senso se guardi sql.html al momento è quasi illeggibile l'html, con markdown non devi pensare all'indentazione etc

**Comment by Radish0** [comment]
Ok, perfetto. Quindi vorresti che il banale testo che ora è nei paragrafi sia riscritto utilizzando il markdown?

**Comment by giomape** [comment]
Potrei fare le prime due o l'ultima

**Comment by Radish0** [comment]
La prima la faccio io :)

**Comment by giomape** [comment]
Va bene. Io faccio l'ultima

**Comment by lorenzobotti** [comment]
Sì, tradurre l'html che abbiamo in markdown, se riesci a committarlo, poi con vscode puoi anche avere l'anteprima in tempo reale

**Comment by lorenzobotti** [comment]
io faccio il capitolo su sql
